services:
  ocr:
    build: .
    container_name: ocr
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocr.entrypoints=websecure"
      - 'traefik.http.routers.ocr.rule=Host(`ocr.xsooi.com`)'
      - "traefik.http.routers.ocr.tls=true"
      - "traefik.http.routers.ocr.tls.certresolver=myresolver"
      - "traefik.http.services.ocr.loadbalancer.server.port=8000"
    networks:
      - proxy

networks:
  proxy:
    external: true
