global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          device_id: mini-orbstack-vm
          platform: linux
          role: container-runtime

  - job_name: 'mini-macos'
    static_configs:
      - targets: ['host.docker.internal:9102']
        labels:
          role: host

  - job_name: 'external-volume'
    static_configs:
      - targets: ['host.docker.internal:9104']
        labels:
          role: host
          platform: darwin

  - job_name: 'mac-power'
    static_configs:
      - targets: ['host.docker.internal:9103']
        labels:
          role: host

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://me.xsooi.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox-exporter:9115']
