---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/
- datetime:
    text_size: x1
    format:
      timeStyle: short
      dateStyle: short

- resources:
    cpu: true
    memory: true
    disk: /

# - search:
#     provider: duckduckgo
#     target: _blank
